### ISSUE TITLE
Having bug on changing dimensions in my browser

### ISSUE THREAD

**Issue by vitorleonel** [paulcollett/vue-masonry-css#3]
Hi,

In my portal (see on https://www.treinarfrontend.com) i'm having a problem resizing the browser window, the elements disappear when the viewport changes, and it is necessary to refresh the page so it recalculates the new widths.

Thank you!

**Comment by paulcollett** [comment]
Thanks for reporting, this definitely shouldn't be happening. By any chance could you post the template code your using?

I'll help look into it!

**Comment by vitorleonel** [comment]
I used like this:

`
<masonry
    :cols="{default: 4, 1400: 3, 768: 2, 576: 1}"
    :gutter="30"
    v-infinite-scroll="loadMore"
    infinite-scroll-disabled="busy"
    infinite-scroll-distance="10"
>
    <div class="link" v-for="(link, key) in links" :key="key">
        <app-link :link="link" :user_id="user_id"></app-link>
    </div>
</masonry>
`

**Comment by paulcollett** [comment]
Does the masonry work without infinate scroll? If so most likley some conflict between the two

**Comment by kyuumeitai** [comment]
Hello. Same happened to me, I have a module inside masonry and it also disappears, but strange enough, if you put hard content it doesn't.

**Comment by paulcollett** [comment]
@kyuumeitai, out of curiosity which module are you using inside `masonry`?

**Comment by zevdg** [comment]
I'm running into this issue as well.  I'll try to make a minimal example and post it here.  In the meantime, I noticed something interesting while debugging this.  In my case, the elements only disappeared the first time this.displayColumns changed and then they reappeared on the next change of that variable.  

I added some debugging to the render function to figure out what made that 2nd render different from the rest and noticed that every other time that variable is changed, the render function is called twice in a row.  The time that it hides all the children, it is only called once.  I don't fully understand why it is doing this yet, but i figured i'd drop the info here in case it gives someone else an epiphany.

**Comment by paulcollett** [comment]
Interesting find @zevdg. A minimal example would be great

**Comment by zevdg** [comment]
ok, the double render was a red herring.  it wasn't rendering twice when it should have been because the children  weren't being rendered.  not the other way around.

The root bug for me was in Vue itself.  Upgrading vue to v2.5.4 or greater fixed the problem for me.  I suspect that [this commit](https://github.com/vuejs/vue/commit/13196b25b8a0a84b3936982177195d2e04f13f79) mentioned in the v2.5.4 changelog is what fixes the root issue.

If anyone is curious and wants to reproduce the issue, I've thrown together [this repo](https://github.com/zevdg/vue-slot-bug) for you.
